spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser

    servlet:
      multipart:
        enabled: true
        location: C:\\upload
        max-request-size: 30MB
        max-file-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
#    cache: false
    prefix: file:src/main/resources/templates/